### ISSUE TITLE
在ha0.74.2中报错

### ISSUE THREAD

**Issue by ZHonry** [syjjx/HA_Esxi#1]
最近两天升级到了ha最新版，结果发现大大的这个插件用不了了，日志发现提示是啥类型问题

 emmm。。。不懂代码
`2018-07-30` 12:00:12 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform ha_vcenter
Traceback (most recent call last):
  File "/root/.homeassistant/custom_components/sensor/ha_vcenter.py", line 422, in _VmInfo
    cpuUsage = 100 * float(stats.overallCpuUsage)/float(summary.runtime.maxCpuUsage) + ""
TypeError: float() argument must be a string or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/helpers/entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.homeassistant/custom_components/sensor/ha_vcenter.py", line 140, in setup_platform
    client.start(hass)
  File "/root/.homeassistant/custom_components/sensor/ha_vcenter.py", line 258, in start
    self.run(dt_util.now())
  File "/root/.homeassistant/custom_components/sensor/ha_vcenter.py", line 517, in run
    self._VmInfo(vm, content, vchtime, self._interval, perf_dict, tags)
  File "/root/.homeassistant/custom_components/sensor/ha_vcenter.py", line 480, in _VmInfo
    _LOGGER.error( "Unable to access information for host: ", vm.name)
  File "/usr/lib/python3.5/logging/__init__.py", line 1309, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1416, in _log
    self.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1426, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1488, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 856, in handle
    self.emit(record)
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/components/system_log/__init__.py", line 131, in emit
    entry = self._create_entry(record, stack)
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/components/system_log/__init__.py", line 114, in _create_entry
    'message': record.getMessage(),
  File "/usr/lib/python3.5/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting`

错误代码如上，望大大更新，(*❦ω❦)

**Comment by wsyccc** [comment]
进入Homeassistant python virtual environment 
Run
pip install --upgrade pyvmomi
然后重启一下就好了

**Comment by ZHonry** [comment]
好的，我试试，谢谢啦
