### ISSUE TITLE
networkTx值无法获得造成启动失败

### ISSUE THREAD

**Issue by sjtuross** [syjjx/HA_Esxi#2]
HA启动时，有时会无法获得networkTx值，造成platform初始化失败，以下是错误信息
```
Error while setting up platform ha_vcenter
Traceback (most recent call last):
  File "/config/custom_components/sensor/ha_vcenter.py", line 382, in _HostInformation
    networkTx = (float(sum(statNetworkTx[0].value[0].value) * 8 * 1024) / statInt)
TypeError: 'bool' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/sensor/ha_vcenter.py", line 354, in _ComputeResourceInformation
    self._HostInformation(host,datacenter_name,computeResource_name,content,perf_dict,vchtime,interval)
  File "/config/custom_components/sensor/ha_vcenter.py", line 391, in _HostInformation
    _LOGGER.error( "Unable to access information for host: ", host.name)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1336, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1443, in _log
    self.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1453, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1515, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 864, in handle
    self.emit(record)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/system_log/__init__.py", line 130, in emit
    entry = self._create_entry(record, stack)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/system_log/__init__.py", line 113, in _create_entry
    'message': record.getMessage(),
  File "/usr/local/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

**Comment by sjtuross** [comment]
解决了，照着vm部分给host的变量也加上判断
```
statNetworkTx = self._BuildQuery(content, vchtime, (self._perf_id(perf_dict, 'net.transmitted.average')), "", host, interval)
if statNetworkTx!=False:
    networkTx = (float(sum(statNetworkTx[0].value[0].value) * 8 * 1024) / statInt)
else:
    networkTx = 0

statNetworkRx = self._BuildQuery(content, vchtime, (self._perf_id(perf_dict, 'net.received.average')), "", host, interval)
if statNetworkRx!=False:
    networkRx = (float(sum(statNetworkRx[0].value[0].value) * 8 * 1024) / statInt)
else:
    networkRx = 0
```
